title: Alcohol Free
author: Bernice Fung
email: bfung@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  Twice is a 9 member girl group under JYP Entertainment and debuted in 2015 with their hit song Like Ooh-Ahh.

# social links
github_username:  beernice

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
