title: Alcohol Free
author: Bernice Fung
email: bfung@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  TWICE is a K-Pop girl group produced by JYP Entertainment through the reality program [SIXTEEN].   The group is composed of 9 members: NAYEON, JEONGYEON, MOMO, SANA, JIHYO, MINA, DAHYUN, CHAEYOUNG, and TZUYU.

# social links
github_username:  beernice

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-cayman
